project:
  type: website
  output-dir: "docs"

website:
  title: "Cristóbal Ortiz Vilches"
  navbar:
    left: 
      - text: "Home"
        file: index.qmd
      - text: "CV"
        file: cv-cov.qmd
      - text: "Works"
        file: works.qmd
    right:
      - icon: github
        href: https://github.com/cristobalortizvilches
      - icon: linkedin
        href: https://www.linkedin.com/in/cristobalortizvilches/
format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css

editor: visual

