project:
  type: website
  output-dir: "docs"

website:
  title: "Cristóbal Ortiz Vilches"
  navbar:
    right: 
     - text: About me
       menu:
         - text: "CV"
           file: cv-cov.qmd
         - text: "Values"
         - text: "Archive"
         - text: "Notes"
     - text: Research
       menu:
         - text: "Publications"
         - text: "Projects"
         - text: "Outreach"
         - text: "Achievments"
    left: 
      - text: "Works"
        file: works.qmd
format:
  html:
    theme:
      - sandstone
      - brand
    css: styles.css

editor: visual

